window.TRAIL_CONFIG = {
  SUPABASE_URL: 'https://YOUR_PROJECT.supabase.co',
  SUPABASE_PUBLISHABLE_KEY: 'YOUR_SUPABASE_PUBLISHABLE_OR_ANON_KEY',
  APP_NAME: 'Trail RC Challenge',
  LINE_LIFF_ID: ''
};
